name: regenerate

on:
  workflow_dispatch:
  schedule:
    - cron: 0 1 * * *

jobs:
  regenerate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22.18.0

      - run: pnpm install

      - run: pnpm start
        id: build

      - uses: EndBug/add-and-commit@v9
        if: ${{ steps.build.outputs.updated == 'true' }}
        with:
          author_name: GitHub Action
          author_email: github-actions[bot]@users.noreply.github.com
          message: |
            chore: update addon to build ${{ steps.build.outputs.build }}
          tag: v${{ steps.build.outputs.version }}

      - uses: BigWigsMods/packager@master
        if: ${{ steps.build.outputs.updated == 'true' }}
        env:
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
          WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
          WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
